### ISSUE TITLE
Todo list of bugs and minor features:

### ISSUE THREAD

**Issue by Sunconure11** [Sunconure11/alaskanativecraft#4]
- [x] Fix harpoons not being able to be thrown
- [x] Fix harpoons not respecting being able to be returned to a user if a lead is attached
- [x] Fix parrots not becoming ptarmigans if exposed to snow
- [x] Dogsleds are barely functional and could be more intuitive to use.
- [ ] Add nether variants of dog sleds from the woods there
- [ ] Add mangrove variant of dog sleds
- [x] Fix config not showing in Mod Menu
- [x] Fix Labrador tea plants not dropping leaves when bonemealed
- [x] Drying rack recipes do not show up in REI
- [x] REI info tabs for stuff like akutaq do not show up
- [ ] Driftwood planks?
- [x] Drying rack has some rendering error
